CREATE TYPE sexo_enum AS ENUM ('M', 'F', 'Otro');
---CREATE TYPE tipo_de_customer AS ENUM ('BUYER', 'SELLER', 'BOTH');

CREATE TABLE CUSTOMER (
USER_ID SERIAL NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL, 
EMAIL VARCHAR(255) UNIQUE NOT NULL,
SEXO sexo_enum NOT NULL,
TELEFONO VARCHAR(255),
FECHA_NACIMIENTO DATE,
DOCUMENTO BIGINT unique not NULL, 
TIPO VARCHAR (255) NOT NULL
);



CREATE TABLE SELLER (
SELLER_ID INT NOT NULL PRIMARY KEY, 
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER (USER_ID)
);



CREATE TABLE BUYER (
BUYER_ID INT NOT NULL PRIMARY KEY,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER (USER_ID)
);

CREATE TABLE ORDERS (
ORDER_ID SERIAL NOT NULL PRIMARY KEY,
SELLER_ID INT NOT NULL, 
FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID),
ORDER_DATE DATE NOT NULL, 
TOTAL_BILL FLOAT NOT NULL, 
STORE VARCHAR(255), 
DIRECCION VARCHAR(255),
ZIP_CODE BIGINT,
BUYER_ID INT NOT NULL,
FOREIGN KEY (BUYER_ID) REFERENCES BUYER (BUYER_ID)
);

CREATE TABLE CATEGORIA (
CATEGORIA_ID SERIAL NOT NULL PRIMARY KEY,
CATEGORIA_1 VARCHAR(255) NOT NULL,
CATEGORIA_2 VARCHAR(255) NOT NULL,
CATEGORIA_3 VARCHAR(255)
);

CREATE TABLE PRODUCTO (
  PRODUCTO_ID SERIAL PRIMARY KEY,
  NOMBRE VARCHAR(255) NOT NULL,
  CATEGORIA_ID INT NOT NULL,
  PRECIO FLOAT NOT NULL,
  PESO FLOAT DEFAULT 100,
  FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID)
);

CREATE TABLE ITEM (
ITEM_ID SERIAL NOT NULL PRIMARY KEY,
ORDER_ID SERIAL NOT NULL,
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
PRODUCTO_ID INT not null ,
foreign key (PRODUCTO_ID) references PRODUCTO(PRODUCTO_ID),
CANTIDAD INT default 1
);

create table FINALDIA (
FINALDIA_ID SERIAL not null primary key, 
NOMBRE VARCHAR(255) NOT NULL,
PRODUCTO_ID INT not null,
PRECIO FLOAT NOT NULL,
FECHA DATE not null,
foreign key (PRODUCTO_ID) references PRODUCTO(PRODUCTO_ID)
);

















