CREATE TABLE CUSTOMER (
USER_ID INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(255) NOT NULL,
APELLIDO VARCHAR(255) NOT NULL, 
EMAIL VARCHAR(255) UNIQUE NOT NULL,
SEXO VARCHAR(255),
TELEFONO VARCHAR(255),
FECHA_NACIMIENTO DATE,
DOCUMENTO LONG, 
TIPO VARCHAR (255) NOT NULL
);


CREATE TABLE SELLER (
SELLER_ID INT NOT NULL PRIMARY KEY, 
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER (USER_ID)
);

CREATE TABLE BUYER (
BUYER_ID INT NOT NULL PRIMARY KEY,
USER_ID INT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES CUSTOMER (USER_ID)
);

CREATE TABLE ORDERS (
ORDER_ID INT NOT NULL PRIMARY KEY,
SELLER_ID INT NOT NULL, 
FOREIGN KEY (SELLER_ID) REFERENCES SELLER (SELLER_ID),
ORDER_DATE DATE NOT NULL, 
TOTAL_BILL FLOAT NOT NULL, 
STORE VARCHAR(255), 
DIRECCION VARCHAR(255),
ZIP_CODE LONG
BUYER_ID INT NOT NULL,
FOREIGN KEY (BUYER_ID) REFERENCES BUYER (BUYER_ID),
);

CREATE TABLE ITEM (
ITEM_ID INT NOT NULL PRIMARY KEY,
ORDER_ID INT NOT NULL,
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
ITEM_ID INT NOT NULL, 
NOMBRE VARCHAR(255) NOT NULL,
CATEGORIA_ID INT NOT NULL,
FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (CATEGORIA_ID),
PRECIO FLOAT NOT NULL,
PESO NOT NULL DEFAULT 100,
STOCK LONG
);

CREATE TABLE CATEGORIA (
CATEGORIA_ID INT NOT NULL,
CATEGORIA_1 VARCHAR(255) NOT NULL,
CATEGORIA_2 VARCHAR(255) NOT NULL,
CATEGORIA_3 VARCHAR(255) NOT NULL,
);



































